# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b7e0bc012418a940f80e017c86102bade4ab8cebaa0114b02b02096fdc700e7984d4a3bc12406cb8da340f0115e8e14f507f40a9d50a66e7a68872aa08fb5ce

test:
  secret_key_base: ed8d166aa736593d6254c8a478f0ac539633828e6914394b5c6b4a8b735950621c2a7616f273b3bce56e2dfac4a8695f54bd33494dd207795c0b9c07596eccc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
